apiVersion: kubecontrolplane.config.openshift.io/v1
kind: KubeAPIServerConfig
# This file is intentionally blank, and only exists to satisfy
# library-go's GenericOptions.ApplyTo(). To change overrides for
# post-bootstrap configuration, update
# bindata/v4.1.0/kube-apiserver/config-overrides.yaml.
